### ISSUE TITLE
Sponsorship to move this project forwward

### ISSUE THREAD

**Issue by mattheworiordan** [Itaybre/CameraController#72]
This is a great utility and I'd like to say thanks for building this app, I used it every day.

However, I see the project has seemed to have stalled with some open PRs and numerous issues.  

Would you consider getting paid to further this project?  Would something like [Github Sponsors](https://github.com/sponsors) be worth looking at so that we can contribute to moving this project forward?

**Comment by Itaybre** [comment]
This year I have been very busy with my thesis so I have neglected a little bit this project.
Fortunately next month I will be completing it, so I will have more free time.

Regarding GitHub Sponsors, I have been recently [accepted](https://github.com/sponsors/Itaybre) but since I didn't change anything in the project, I haven't added it to the repo.
