### ISSUE TITLE
Display current slider values (UVC values)

### ISSUE THREAD

**Issue by JayFoxRox** [Itaybre/CameraController#78]
I'd like to reproduce the work in https://ciko.io/posts/cheap_usb_hdmi/ and https://ciko.io/posts/cheap_usb_hdmi_2/

However, while CameraController can change my capture device settings (although I don't have the "hue" parameter?), I have no way of seeing the current values (= reproducing the values by someone else).
This makes it extremly difficult to reproduce the results (or even to experiment with a setting and then go back to the old value, without creating a profile).

In an ideal world there'd be a way to show the technical UVC details (which are more important to me) if enabled under preferences, otherwise show percentages (which would be more important for the average user).

**Comment by Itaybre** [comment]
This feature was implemented in this PR: https://github.com/Itaybre/CameraController/pull/35/files#diff-3fc0120903ade031e9cf8976e371da4027e69a9130fa517589c417f0c6c15c05
You can press the name of the button to enable / disable manual input.

I didn't add HUE control because most cameras don't support it, can't say I considered video capture cards when building this.
But adding support for it should be fairly easy with a couple lines of code:
- Add this to `ImageView.swift` after line 49:
```swift
HStack {
    Toggle(isOn: $controller.hueAuto.isEnabled) {
        Text("Auto")
    }
    .disabled(!controller.hueAuto.isCapable)

    Spacer()
    Slider(value: $controller.hue.sliderValue,
           in: controller.hue.minimum...controller.hue.maximum)
        .frame(width: 300, height: 15)
        .disabled(!controller.hue.isCapable)
}
```

- Add this to `DeviceController.swift` after line 20:
```swift
@Published var hue: NumberCaptureDeviceProperty
@Published var hueAuto: BoolCaptureDeviceProperty
```

- Add this to `DeviceController.swift` anywhere inside init (I did in line 46):
```swift
hue = NumberCaptureDeviceProperty(properties.hue)
hueAuto = BoolCaptureDeviceProperty(properties.hueAuto)
```
